/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tcpr.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tcpr.pb-c.h"
void   four_tuple__init
                     (FourTuple         *message)
{
  static FourTuple init_value = FOUR_TUPLE__INIT;
  *message = init_value;
}
size_t four_tuple__get_packed_size
                     (const FourTuple *message)
{
  assert(message->base.descriptor == &four_tuple__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t four_tuple__pack
                     (const FourTuple *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &four_tuple__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t four_tuple__pack_to_buffer
                     (const FourTuple *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &four_tuple__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FourTuple *
       four_tuple__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FourTuple *)
     protobuf_c_message_unpack (&four_tuple__descriptor,
                                allocator, len, data);
}
void   four_tuple__free_unpacked
                     (FourTuple *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &four_tuple__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tcpr_set__init
                     (TcprSet         *message)
{
  static TcprSet init_value = TCPR_SET__INIT;
  *message = init_value;
}
size_t tcpr_set__get_packed_size
                     (const TcprSet *message)
{
  assert(message->base.descriptor == &tcpr_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcpr_set__pack
                     (const TcprSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcpr_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcpr_set__pack_to_buffer
                     (const TcprSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcpr_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TcprSet *
       tcpr_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TcprSet *)
     protobuf_c_message_unpack (&tcpr_set__descriptor,
                                allocator, len, data);
}
void   tcpr_set__free_unpacked
                     (TcprSet *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tcpr_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tcpr_get_init__init
                     (TcprGetInit         *message)
{
  static TcprGetInit init_value = TCPR_GET_INIT__INIT;
  *message = init_value;
}
size_t tcpr_get_init__get_packed_size
                     (const TcprGetInit *message)
{
  assert(message->base.descriptor == &tcpr_get_init__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcpr_get_init__pack
                     (const TcprGetInit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcpr_get_init__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcpr_get_init__pack_to_buffer
                     (const TcprGetInit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcpr_get_init__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TcprGetInit *
       tcpr_get_init__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TcprGetInit *)
     protobuf_c_message_unpack (&tcpr_get_init__descriptor,
                                allocator, len, data);
}
void   tcpr_get_init__free_unpacked
                     (TcprGetInit *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tcpr_get_init__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tcpr_get_ack__init
                     (TcprGetAck         *message)
{
  static TcprGetAck init_value = TCPR_GET_ACK__INIT;
  *message = init_value;
}
size_t tcpr_get_ack__get_packed_size
                     (const TcprGetAck *message)
{
  assert(message->base.descriptor == &tcpr_get_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcpr_get_ack__pack
                     (const TcprGetAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcpr_get_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcpr_get_ack__pack_to_buffer
                     (const TcprGetAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcpr_get_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TcprGetAck *
       tcpr_get_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TcprGetAck *)
     protobuf_c_message_unpack (&tcpr_get_ack__descriptor,
                                allocator, len, data);
}
void   tcpr_get_ack__free_unpacked
                     (TcprGetAck *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tcpr_get_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tcpr_get_list__init
                     (TcprGetList         *message)
{
  static TcprGetList init_value = TCPR_GET_LIST__INIT;
  *message = init_value;
}
size_t tcpr_get_list__get_packed_size
                     (const TcprGetList *message)
{
  assert(message->base.descriptor == &tcpr_get_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcpr_get_list__pack
                     (const TcprGetList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcpr_get_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcpr_get_list__pack_to_buffer
                     (const TcprGetList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcpr_get_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TcprGetList *
       tcpr_get_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TcprGetList *)
     protobuf_c_message_unpack (&tcpr_get_list__descriptor,
                                allocator, len, data);
}
void   tcpr_get_list__free_unpacked
                     (TcprGetList *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tcpr_get_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tcpr_get_list_response__init
                     (TcprGetListResponse         *message)
{
  static TcprGetListResponse init_value = TCPR_GET_LIST_RESPONSE__INIT;
  *message = init_value;
}
size_t tcpr_get_list_response__get_packed_size
                     (const TcprGetListResponse *message)
{
  assert(message->base.descriptor == &tcpr_get_list_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcpr_get_list_response__pack
                     (const TcprGetListResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcpr_get_list_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcpr_get_list_response__pack_to_buffer
                     (const TcprGetListResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcpr_get_list_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TcprGetListResponse *
       tcpr_get_list_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TcprGetListResponse *)
     protobuf_c_message_unpack (&tcpr_get_list_response__descriptor,
                                allocator, len, data);
}
void   tcpr_get_list_response__free_unpacked
                     (TcprGetListResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tcpr_get_list_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tcpr_set_response__init
                     (TcprSetResponse         *message)
{
  static TcprSetResponse init_value = TCPR_SET_RESPONSE__INIT;
  *message = init_value;
}
size_t tcpr_set_response__get_packed_size
                     (const TcprSetResponse *message)
{
  assert(message->base.descriptor == &tcpr_set_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcpr_set_response__pack
                     (const TcprSetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcpr_set_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcpr_set_response__pack_to_buffer
                     (const TcprSetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcpr_set_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TcprSetResponse *
       tcpr_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TcprSetResponse *)
     protobuf_c_message_unpack (&tcpr_set_response__descriptor,
                                allocator, len, data);
}
void   tcpr_set_response__free_unpacked
                     (TcprSetResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tcpr_set_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tcpr_get_init_response__init
                     (TcprGetInitResponse         *message)
{
  static TcprGetInitResponse init_value = TCPR_GET_INIT_RESPONSE__INIT;
  *message = init_value;
}
size_t tcpr_get_init_response__get_packed_size
                     (const TcprGetInitResponse *message)
{
  assert(message->base.descriptor == &tcpr_get_init_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcpr_get_init_response__pack
                     (const TcprGetInitResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcpr_get_init_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcpr_get_init_response__pack_to_buffer
                     (const TcprGetInitResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcpr_get_init_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TcprGetInitResponse *
       tcpr_get_init_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TcprGetInitResponse *)
     protobuf_c_message_unpack (&tcpr_get_init_response__descriptor,
                                allocator, len, data);
}
void   tcpr_get_init_response__free_unpacked
                     (TcprGetInitResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tcpr_get_init_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tcpr_get_ack_response__init
                     (TcprGetAckResponse         *message)
{
  static TcprGetAckResponse init_value = TCPR_GET_ACK_RESPONSE__INIT;
  *message = init_value;
}
size_t tcpr_get_ack_response__get_packed_size
                     (const TcprGetAckResponse *message)
{
  assert(message->base.descriptor == &tcpr_get_ack_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcpr_get_ack_response__pack
                     (const TcprGetAckResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcpr_get_ack_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcpr_get_ack_response__pack_to_buffer
                     (const TcprGetAckResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcpr_get_ack_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TcprGetAckResponse *
       tcpr_get_ack_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TcprGetAckResponse *)
     protobuf_c_message_unpack (&tcpr_get_ack_response__descriptor,
                                allocator, len, data);
}
void   tcpr_get_ack_response__free_unpacked
                     (TcprGetAckResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tcpr_get_ack_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tcpr__init
                     (Tcpr         *message)
{
  static Tcpr init_value = TCPR__INIT;
  *message = init_value;
}
size_t tcpr__get_packed_size
                     (const Tcpr *message)
{
  assert(message->base.descriptor == &tcpr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcpr__pack
                     (const Tcpr *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcpr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcpr__pack_to_buffer
                     (const Tcpr *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcpr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tcpr *
       tcpr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tcpr *)
     protobuf_c_message_unpack (&tcpr__descriptor,
                                allocator, len, data);
}
void   tcpr__free_unpacked
                     (Tcpr *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tcpr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor four_tuple__field_descriptors[4] =
{
  {
    "local_ip",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FourTuple, local_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_ip",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FourTuple, remote_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_port",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FourTuple, has_local_port),
    offsetof(FourTuple, local_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_port",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FourTuple, has_remote_port),
    offsetof(FourTuple, remote_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned four_tuple__field_indices_by_name[] = {
  0,   /* field[0] = local_ip */
  2,   /* field[2] = local_port */
  1,   /* field[1] = remote_ip */
  3,   /* field[3] = remote_port */
};
static const ProtobufCIntRange four_tuple__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor four_tuple__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "four_tuple",
  "FourTuple",
  "FourTuple",
  "",
  sizeof(FourTuple),
  4,
  four_tuple__field_descriptors,
  four_tuple__field_indices_by_name,
  1,  four_tuple__number_ranges,
  (ProtobufCMessageInit) four_tuple__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tcpr_set__field_descriptors[4] =
{
  {
    "connection",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TcprSet, connection),
    &four_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sack_enabled",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TcprSet, has_sack_enabled),
    offsetof(TcprSet, sack_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_segment_size",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TcprSet, has_max_segment_size),
    offsetof(TcprSet, max_segment_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "window_scaling",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TcprSet, has_window_scaling),
    offsetof(TcprSet, window_scaling),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tcpr_set__field_indices_by_name[] = {
  0,   /* field[0] = connection */
  2,   /* field[2] = max_segment_size */
  1,   /* field[1] = sack_enabled */
  3,   /* field[3] = window_scaling */
};
static const ProtobufCIntRange tcpr_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor tcpr_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tcpr_set",
  "TcprSet",
  "TcprSet",
  "",
  sizeof(TcprSet),
  4,
  tcpr_set__field_descriptors,
  tcpr_set__field_indices_by_name,
  1,  tcpr_set__number_ranges,
  (ProtobufCMessageInit) tcpr_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tcpr_get_init__field_descriptors[1] =
{
  {
    "connection",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TcprGetInit, connection),
    &four_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tcpr_get_init__field_indices_by_name[] = {
  0,   /* field[0] = connection */
};
static const ProtobufCIntRange tcpr_get_init__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tcpr_get_init__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tcpr_get_init",
  "TcprGetInit",
  "TcprGetInit",
  "",
  sizeof(TcprGetInit),
  1,
  tcpr_get_init__field_descriptors,
  tcpr_get_init__field_indices_by_name,
  1,  tcpr_get_init__number_ranges,
  (ProtobufCMessageInit) tcpr_get_init__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tcpr_get_ack__field_descriptors[1] =
{
  {
    "connection",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TcprGetAck, connection),
    &four_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tcpr_get_ack__field_indices_by_name[] = {
  0,   /* field[0] = connection */
};
static const ProtobufCIntRange tcpr_get_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tcpr_get_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tcpr_get_ack",
  "TcprGetAck",
  "TcprGetAck",
  "",
  sizeof(TcprGetAck),
  1,
  tcpr_get_ack__field_descriptors,
  tcpr_get_ack__field_indices_by_name,
  1,  tcpr_get_ack__number_ranges,
  (ProtobufCMessageInit) tcpr_get_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define tcpr_get_list__field_descriptors NULL
#define tcpr_get_list__field_indices_by_name NULL
#define tcpr_get_list__number_ranges NULL
const ProtobufCMessageDescriptor tcpr_get_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tcpr_get_list",
  "TcprGetList",
  "TcprGetList",
  "",
  sizeof(TcprGetList),
  0,
  tcpr_get_list__field_descriptors,
  tcpr_get_list__field_indices_by_name,
  0,  tcpr_get_list__number_ranges,
  (ProtobufCMessageInit) tcpr_get_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tcpr_get_list_response__field_descriptors[1] =
{
  {
    "connections",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TcprGetListResponse, n_connections),
    offsetof(TcprGetListResponse, connections),
    &tcpr_set__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tcpr_get_list_response__field_indices_by_name[] = {
  0,   /* field[0] = connections */
};
static const ProtobufCIntRange tcpr_get_list_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tcpr_get_list_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tcpr_get_list_response",
  "TcprGetListResponse",
  "TcprGetListResponse",
  "",
  sizeof(TcprGetListResponse),
  1,
  tcpr_get_list_response__field_descriptors,
  tcpr_get_list_response__field_indices_by_name,
  1,  tcpr_get_list_response__number_ranges,
  (ProtobufCMessageInit) tcpr_get_list_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tcpr_set_response__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(TcprSetResponse, has_status),
    offsetof(TcprSetResponse, status),
    &status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tcpr_set_response__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange tcpr_set_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tcpr_set_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tcpr_set_response",
  "TcprSetResponse",
  "TcprSetResponse",
  "",
  sizeof(TcprSetResponse),
  1,
  tcpr_set_response__field_descriptors,
  tcpr_set_response__field_indices_by_name,
  1,  tcpr_set_response__number_ranges,
  (ProtobufCMessageInit) tcpr_set_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tcpr_get_init_response__field_descriptors[5] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(TcprGetInitResponse, has_status),
    offsetof(TcprGetInitResponse, status),
    &status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initial_seq",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TcprGetInitResponse, has_initial_seq),
    offsetof(TcprGetInitResponse, initial_seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sack_enabled",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TcprGetInitResponse, has_sack_enabled),
    offsetof(TcprGetInitResponse, sack_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_segment_size",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TcprGetInitResponse, has_max_segment_size),
    offsetof(TcprGetInitResponse, max_segment_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "window_scaling",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TcprGetInitResponse, has_window_scaling),
    offsetof(TcprGetInitResponse, window_scaling),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tcpr_get_init_response__field_indices_by_name[] = {
  1,   /* field[1] = initial_seq */
  3,   /* field[3] = max_segment_size */
  2,   /* field[2] = sack_enabled */
  0,   /* field[0] = status */
  4,   /* field[4] = window_scaling */
};
static const ProtobufCIntRange tcpr_get_init_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor tcpr_get_init_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tcpr_get_init_response",
  "TcprGetInitResponse",
  "TcprGetInitResponse",
  "",
  sizeof(TcprGetInitResponse),
  5,
  tcpr_get_init_response__field_descriptors,
  tcpr_get_init_response__field_indices_by_name,
  1,  tcpr_get_init_response__number_ranges,
  (ProtobufCMessageInit) tcpr_get_init_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tcpr_get_ack_response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(TcprGetAckResponse, has_status),
    offsetof(TcprGetAckResponse, status),
    &status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_ack",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TcprGetAckResponse, has_current_ack),
    offsetof(TcprGetAckResponse, current_ack),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tcpr_get_ack_response__field_indices_by_name[] = {
  1,   /* field[1] = current_ack */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange tcpr_get_ack_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tcpr_get_ack_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tcpr_get_ack_response",
  "TcprGetAckResponse",
  "TcprGetAckResponse",
  "",
  sizeof(TcprGetAckResponse),
  2,
  tcpr_get_ack_response__field_descriptors,
  tcpr_get_ack_response__field_indices_by_name,
  1,  tcpr_get_ack_response__number_ranges,
  (ProtobufCMessageInit) tcpr_get_ack_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tcpr__field_descriptors[8] =
{
  {
    "get_init",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tcpr, message_case),
    offsetof(Tcpr, get_init),
    &tcpr_get_init__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_init_response",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tcpr, message_case),
    offsetof(Tcpr, get_init_response),
    &tcpr_get_init_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_ack",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tcpr, message_case),
    offsetof(Tcpr, get_ack),
    &tcpr_get_ack__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_ack_response",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tcpr, message_case),
    offsetof(Tcpr, get_ack_response),
    &tcpr_get_ack_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_list",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tcpr, message_case),
    offsetof(Tcpr, get_list),
    &tcpr_get_list__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_list_response",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tcpr, message_case),
    offsetof(Tcpr, get_list_response),
    &tcpr_get_list_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tcpr, message_case),
    offsetof(Tcpr, set),
    &tcpr_set__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_response",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tcpr, message_case),
    offsetof(Tcpr, set_response),
    &tcpr_set_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tcpr__field_indices_by_name[] = {
  2,   /* field[2] = get_ack */
  3,   /* field[3] = get_ack_response */
  0,   /* field[0] = get_init */
  1,   /* field[1] = get_init_response */
  4,   /* field[4] = get_list */
  5,   /* field[5] = get_list_response */
  6,   /* field[6] = set */
  7,   /* field[7] = set_response */
};
static const ProtobufCIntRange tcpr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor tcpr__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tcpr",
  "Tcpr",
  "Tcpr",
  "",
  sizeof(Tcpr),
  8,
  tcpr__field_descriptors,
  tcpr__field_indices_by_name,
  1,  tcpr__number_ranges,
  (ProtobufCMessageInit) tcpr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue status__enum_values_by_number[4] =
{
  { "SUCCESS", "STATUS__SUCCESS", 0 },
  { "FAILED_EXISTS", "STATUS__FAILED_EXISTS", 1 },
  { "FAILED_NOT_FOUND", "STATUS__FAILED_NOT_FOUND", 2 },
  { "FAILED", "STATUS__FAILED", 3 },
};
static const ProtobufCIntRange status__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex status__enum_values_by_name[4] =
{
  { "FAILED", 3 },
  { "FAILED_EXISTS", 1 },
  { "FAILED_NOT_FOUND", 2 },
  { "SUCCESS", 0 },
};
const ProtobufCEnumDescriptor status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "status",
  "status",
  "Status",
  "",
  4,
  status__enum_values_by_number,
  4,
  status__enum_values_by_name,
  1,
  status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
