# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tcpr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tcpr.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\ntcpr.proto\"\xa8\x01\n\x06\x63lient\x12\x10\n\x08local_ip\x18\x01 \x01(\t\x12\x11\n\tremote_ip\x18\x02 \x01(\t\x12\x12\n\nlocal_port\x18\x03 \x01(\r\x12\x13\n\x0bremote_port\x18\x04 \x01(\r\x12\x11\n\tlocal_seq\x18\x05 \x01(\r\x12\x12\n\nremote_seq\x18\x06 \x01(\r\x12\x16\n\x0einit_local_seq\x18\x07 \x01(\r\x12\x11\n\tis_server\x18\x08 \x01(\x08\"-\n\x11tcpr_get_response\x12\x18\n\x07\x63lients\x18\x01 \x03(\x0b\x32\x07.client\"$\n\x08tcpr_set\x12\x18\n\x07\x63lients\x18\x01 \x03(\x0b\x32\x07.client\"X\n\x08tcpr_get\x12\x10\n\x08local_ip\x18\x01 \x01(\t\x12\x11\n\tremote_ip\x18\x02 \x01(\t\x12\x12\n\nlocal_port\x18\x03 \x01(\r\x12\x13\n\x0bremote_port\x18\x04 \x01(\r\"\x13\n\x11tcpr_set_response\"\x9d\x01\n\x04tcpr\x12\x18\n\x03get\x18\x01 \x01(\x0b\x32\t.tcpr_getH\x00\x12\x18\n\x03set\x18\x02 \x01(\x0b\x32\t.tcpr_setH\x00\x12*\n\x0cget_response\x18\x03 \x01(\x0b\x32\x12.tcpr_get_responseH\x00\x12*\n\x0cset_response\x18\x04 \x01(\x0b\x32\x12.tcpr_set_responseH\x00\x42\t\n\x07messageb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CLIENT = _descriptor.Descriptor(
  name='client',
  full_name='client',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_ip', full_name='client.local_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remote_ip', full_name='client.remote_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_port', full_name='client.local_port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remote_port', full_name='client.remote_port', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_seq', full_name='client.local_seq', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remote_seq', full_name='client.remote_seq', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='init_local_seq', full_name='client.init_local_seq', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_server', full_name='client.is_server', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=183,
)


_TCPR_GET_RESPONSE = _descriptor.Descriptor(
  name='tcpr_get_response',
  full_name='tcpr_get_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clients', full_name='tcpr_get_response.clients', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=230,
)


_TCPR_SET = _descriptor.Descriptor(
  name='tcpr_set',
  full_name='tcpr_set',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clients', full_name='tcpr_set.clients', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=268,
)


_TCPR_GET = _descriptor.Descriptor(
  name='tcpr_get',
  full_name='tcpr_get',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_ip', full_name='tcpr_get.local_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remote_ip', full_name='tcpr_get.remote_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_port', full_name='tcpr_get.local_port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remote_port', full_name='tcpr_get.remote_port', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=358,
)


_TCPR_SET_RESPONSE = _descriptor.Descriptor(
  name='tcpr_set_response',
  full_name='tcpr_set_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=379,
)


_TCPR = _descriptor.Descriptor(
  name='tcpr',
  full_name='tcpr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='get', full_name='tcpr.get', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set', full_name='tcpr.set', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_response', full_name='tcpr.get_response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set_response', full_name='tcpr.set_response', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='tcpr.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=382,
  serialized_end=539,
)

_TCPR_GET_RESPONSE.fields_by_name['clients'].message_type = _CLIENT
_TCPR_SET.fields_by_name['clients'].message_type = _CLIENT
_TCPR.fields_by_name['get'].message_type = _TCPR_GET
_TCPR.fields_by_name['set'].message_type = _TCPR_SET
_TCPR.fields_by_name['get_response'].message_type = _TCPR_GET_RESPONSE
_TCPR.fields_by_name['set_response'].message_type = _TCPR_SET_RESPONSE
_TCPR.oneofs_by_name['message'].fields.append(
  _TCPR.fields_by_name['get'])
_TCPR.fields_by_name['get'].containing_oneof = _TCPR.oneofs_by_name['message']
_TCPR.oneofs_by_name['message'].fields.append(
  _TCPR.fields_by_name['set'])
_TCPR.fields_by_name['set'].containing_oneof = _TCPR.oneofs_by_name['message']
_TCPR.oneofs_by_name['message'].fields.append(
  _TCPR.fields_by_name['get_response'])
_TCPR.fields_by_name['get_response'].containing_oneof = _TCPR.oneofs_by_name['message']
_TCPR.oneofs_by_name['message'].fields.append(
  _TCPR.fields_by_name['set_response'])
_TCPR.fields_by_name['set_response'].containing_oneof = _TCPR.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['client'] = _CLIENT
DESCRIPTOR.message_types_by_name['tcpr_get_response'] = _TCPR_GET_RESPONSE
DESCRIPTOR.message_types_by_name['tcpr_set'] = _TCPR_SET
DESCRIPTOR.message_types_by_name['tcpr_get'] = _TCPR_GET
DESCRIPTOR.message_types_by_name['tcpr_set_response'] = _TCPR_SET_RESPONSE
DESCRIPTOR.message_types_by_name['tcpr'] = _TCPR

client = _reflection.GeneratedProtocolMessageType('client', (_message.Message,), dict(
  DESCRIPTOR = _CLIENT,
  __module__ = 'tcpr_pb2'
  # @@protoc_insertion_point(class_scope:client)
  ))
_sym_db.RegisterMessage(client)

tcpr_get_response = _reflection.GeneratedProtocolMessageType('tcpr_get_response', (_message.Message,), dict(
  DESCRIPTOR = _TCPR_GET_RESPONSE,
  __module__ = 'tcpr_pb2'
  # @@protoc_insertion_point(class_scope:tcpr_get_response)
  ))
_sym_db.RegisterMessage(tcpr_get_response)

tcpr_set = _reflection.GeneratedProtocolMessageType('tcpr_set', (_message.Message,), dict(
  DESCRIPTOR = _TCPR_SET,
  __module__ = 'tcpr_pb2'
  # @@protoc_insertion_point(class_scope:tcpr_set)
  ))
_sym_db.RegisterMessage(tcpr_set)

tcpr_get = _reflection.GeneratedProtocolMessageType('tcpr_get', (_message.Message,), dict(
  DESCRIPTOR = _TCPR_GET,
  __module__ = 'tcpr_pb2'
  # @@protoc_insertion_point(class_scope:tcpr_get)
  ))
_sym_db.RegisterMessage(tcpr_get)

tcpr_set_response = _reflection.GeneratedProtocolMessageType('tcpr_set_response', (_message.Message,), dict(
  DESCRIPTOR = _TCPR_SET_RESPONSE,
  __module__ = 'tcpr_pb2'
  # @@protoc_insertion_point(class_scope:tcpr_set_response)
  ))
_sym_db.RegisterMessage(tcpr_set_response)

tcpr = _reflection.GeneratedProtocolMessageType('tcpr', (_message.Message,), dict(
  DESCRIPTOR = _TCPR,
  __module__ = 'tcpr_pb2'
  # @@protoc_insertion_point(class_scope:tcpr)
  ))
_sym_db.RegisterMessage(tcpr)


# @@protoc_insertion_point(module_scope)
